import jsPDF from 'jspdf';
import { AIAnalysis } from '@/integrations/supabase/types';

interface ExportData {
  fileName: string;
  documentType: string;
  extractedText: string;
  analysis?: AIAnalysis;
  createdAt?: string;
}

export const exportToPDF = (data: ExportData) => {
  const pdf = new jsPDF();
  let yPosition = 20;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);
  const lineHeight = 7;

  // Helper function to add text with word wrap
  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    pdf.setFontSize(fontSize);
    if (isBold) {
      pdf.setFont('helvetica', 'bold');
    } else {
      pdf.setFont('helvetica', 'normal');
    }
    const lines = pdf.splitTextToSize(text, maxWidth);
    
    lines.forEach((line: string) => {
      if (yPosition > 270) {
        pdf.addPage();
        yPosition = 20;
      }
      pdf.text(line, margin, yPosition);
      yPosition += lineHeight;
    });
  };

  // Helper function to add spacing
  const addSpace = (space: number = 5) => {
    yPosition += space;
    if (yPosition > 270) {
      pdf.addPage();
      yPosition = 20;
    }
  };

  // Helper function to add a line
  const addLine = () => {
    if (yPosition > 270) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 5;
  };

  // Title
  pdf.setFillColor(59, 130, 246); // Primary color
  pdf.rect(0, 0, pageWidth, 40, 'F');
  pdf.setTextColor(255, 255, 255);
  addText('Document Analysis Report', 18, true);
  addSpace(3);
  pdf.setTextColor(0, 0, 0);
  
  addSpace(10);

  // Document Information
  addText('Document Information', 14, true);
  addSpace(3);
  addLine();
  addText(`File Name: ${data.fileName}`, 10, false);
  addText(`Document Type: ${data.documentType}`, 10, false);
  if (data.createdAt) {
    addText(`Processed: ${new Date(data.createdAt).toLocaleString()}`, 10, false);
  }
  addSpace(10);

  // AI Analysis Section
  if (data.analysis) {
    addText('AI Analysis', 14, true);
    addSpace(3);
    addLine();

    // Confidence and Urgency
    if (data.analysis.confidence || data.analysis.urgency) {
      const badges = [];
      if (data.analysis.confidence) badges.push(`Confidence: ${data.analysis.confidence}`);
      if (data.analysis.urgency) badges.push(`Urgency: ${data.analysis.urgency}`);
      if (data.analysis.category) badges.push(`Category: ${data.analysis.category}`);
      addText(badges.join(' | '), 9, false);
      addSpace(5);
    }

    // Summary
    if (data.analysis.summary) {
      addText('Summary', 12, true);
      addSpace(2);
      addText(data.analysis.summary, 10, false);
      addSpace(8);
    }

    // Key Information
    if (data.analysis.keyInformation && data.analysis.keyInformation.length > 0) {
      addText('Key Information', 12, true);
      addSpace(2);
      data.analysis.keyInformation.forEach((info: string) => {
        addText(`• ${info}`, 10, false);
      });
      addSpace(8);
    }

    // Suggested Actions
    if (data.analysis.suggestedActions && data.analysis.suggestedActions.length > 0) {
      addText('Recommended Actions', 12, true);
      addSpace(2);
      data.analysis.suggestedActions.forEach((action: string, idx: number) => {
        addText(`${idx + 1}. ${action}`, 10, false);
      });
      addSpace(10);
    }
  }

  // Extracted Text
  addText('Extracted Text', 14, true);
  addSpace(3);
  addLine();
  
  // Limit extracted text to reasonable length for PDF
  const truncatedText = data.extractedText.length > 3000 
    ? data.extractedText.substring(0, 3000) + '...\n\n[Text truncated for PDF export]'
    : data.extractedText;
  
  addText(truncatedText, 9, false);

  // Footer with page numbers
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(
      `Page ${i} of ${pageCount}`,
      pageWidth / 2,
      pdf.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    pdf.text(
      'Generated by Document Assistant',
      pageWidth - margin,
      pdf.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    );
  }

  // Save the PDF
  const sanitizedFileName = data.fileName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  pdf.save(`analysis_${sanitizedFileName}.pdf`);
};
